#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

#autoload -U compinit
#compinit

# Add brew to PATH, if exists
if [ -d '/home/linuxbrew/.linuxbrew/bin' ]; then
	export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
fi

if [ -f '/home/linuxbrew/.linuxbrew/opt/zsh-git-prompt/zshrc.sh' ]; then
    source "/home/linuxbrew/.linuxbrew/opt/zsh-git-prompt/zshrc.sh"
fi

####
## ==> Pouring zsh-completions--0.35.0.all.bottle.1.tar.gz
## ==> Downloading https://formulae.brew.sh/api/cask.jws.json
## ==> Caveats
## To activate these completions, add the following to your .zshrc:

  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi

## You may also need to force rebuild `zcompdump`:

##  rm -f ~/.zcompdump; compinit

## Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
## to load these completions, you may need to run these commands:

##  chmod go-w '/home/linuxbrew/.linuxbrew/share'
##  chmod -R go-w '/home/linuxbrew/.linuxbrew/share/zsh'
####

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
setopt APPEND_HISTORY
## for sharing history between zsh processes
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

## never ever beep ever
setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0

# colors
autoload -U colors

# save zsh command history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
#setopt appendhistory
setopt SHARE_HISTORY

## flatpak - import flatpak variables and paths
#source /etc/profile.d/flatpak.sh
emulate sh -c 'source /etc/profile'

## pathing
if [ -d '$HOME/bin' ]; then
	PATH=$$HOME/bin:$PATH
fi
if [ -d '$HOME/.local/bin' ]; then
	PATH=$HOME/.local/bin:$PATH
fi

## aliases
alias vim="nvim"
alias vi="nvim"
export EDITOR="nvim"
export VISUAL="nvim"
alias dflip="docker compose down; docker compose up -d; docker compose logs -f"
alias dlogs="docker compose logs -f"

## starship
eval "$(starship init zsh)"
