if [ -d '/home/linuxbrew/.linuxbrew/bin' ]; then
	PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
fi
alias vim="nvim"
alias vi="nvim"
export EDITOR="nvim"
export VISUAL="nvim"
eval "$(starship init zsh)"
alias dflip="docker compose down; docker compose up -d; docker compose logs -f"
alias dlogs="docker compose logs -f"
