---
- name: Install binfiles, oneliners, etc to HOME-bin
  synchronize:
    src: "{{ code_directory }}/dotfiles/bin/"
    dest: ~/bin
    checksum: yes
    archive: no
    recursive: yes
  delegate_to: localhost
