---
- name: Ensure home bin directory exists
  file:
    path: "${HOME}/bin"
    state: directory

      #- name: Ensure home .ssh directory exists
      #file:
      #path: "${HOME}/.ssh"
      #state: directory

- name: Ensure code dictory exists
  file:
    path: "{{ code_directory }}"
    state: directory

- name: Ensure Downloads directory exists
  file:
    path: "${HOME}/Downloads"
    state: directory
