---
- name: Install macos defaults
  copy:
    src: "files/macos-defaults"
    dest: ~/bin/
    mode: 0755
  delegate_to: localhost

- name: Install macos update
  copy:
    src: "files/macos-update"
    dest: ~/bin/
    mode: 0755
  delegate_to: localhost

- name: Extract SpaceVim fonts
  unarchive:
    src: "{{ downloads }}/SourceCodePro.zip"
    dest: /Library/Fonts
  when: spacevim_dir.stat.exists == false

- name: Remove SpaceVim fonts zip
  file:
    path: "{{ downloads }}/SourceCodePro.zip"
    state: absent

#- name: Install pip packages
#  pip:
#    name: boto3
    #extra_args: --user
#  become: yes
