---
- name: Checkout dotfiles repo
  git:
    repo: "{{ dotfiles_giturl }}"
    dest: "{{ code_directory }}/dotfiles/"
    clone: yes
    update: yes

- name: Install static dotfiles
  synchronize:
    src: "{{ code_directory }}/dotfiles/{{ dotfiles_item }}"
    dest: "~/{{ dotfiles_item }}"
    checksum: yes
    archive: no
  with_items:
    - "{{ dotfiles }}"
  loop_control:
    loop_var: dotfiles_item

- name: Adding templated dotfile
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
