---
- name: Checkout dotfiles repo
  git:
    repo: "{{ dotfiles_giturl }}"
    dest: "{{ code_directory }}/dotfiles/"
    clone: yes
    update: yes

- name: Install static dotfiles (will error if you have local changes, this is normal)
  synchronize:
    src: "{{ code_directory }}/dotfiles/{{ dotfiles_item }}"
    dest: "~/{{ dotfiles_item }}"
    checksum: yes
    archive: no
  with_items:
    - "{{ dotfiles }}"
  loop_control:
    loop_var: dotfiles_item

- name: Adding .config dir
  file:
    path: ~/.config
    state: directory

- name: Adding .config/pip dir
  file:
    path: ~/.config/pip
    state: directory

- name: Adding templated dotfile
  copy:
    src: "{{ code_directory }}/dotfiles/pip.conf"
    dest: ~/.config/pip/pip.conf

- name: Adding templated dotfile
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no
